export const IMG = {
  SPLASH: require("../../assets/image/splesh.png"),
  LOGO: require("../../assets/image/logo.png"),
  ONBORD1 : require("../../assets/image/onbording1.png"),
  ONBORD2 : require("../../assets/image/onbording2.png"),
  ONBORD3 : require("../../assets/image/onbording3.png"),
  FB : require("../../assets/image/fb.png"),
  FB2 : require("../../assets/image/fb2.png"),
  GOOGLE : require("../../assets/image/google.png"),
  TAB_HOME : require("../../assets/image/home.png"),
  TAB_FAVORITE : require("../../assets/image/Star.png"),
  TAB_BAG : require("../../assets/image/‌Bag.png"),
  TAB_USER : require("../../assets/image/User.png"),
  REST_COVER : require("../../assets/image/resturant.png"),
  REST_COVER2 : require("../../assets/image/resturant2.png"),
  FIRE : require("../../assets/image/fire.png"),
  OFFER :require("../../assets/image/offer.png"),
  OPTION_HOT : require("../../assets/image/Hotdeal.png"),
  OPTION_FOOD : require("../../assets/image/Newshohoz.png"),
  OPTION_BADGET : require("../../assets/image/Badget.png"),
  OPTION_PREFERENCE : require("../../assets/image/Favourite.png"),
  COFFEE : require("../../assets/image/coffee1.png"),
  COFFEE2 : require("../../assets/image/coffee.png"),
  EGG : require("../../assets/image/egg.png"),
  RICE : require("../../assets/image/Rice.png"),
  ITALIANRICE : require("../../assets/image/Italianrice.png"),
  NOODLEEGG : require("../../assets/image/Italianrice.png"),
  SALAD : require("../../assets/image/Salad.png"),
  PURE : require("../../assets/image/purepng.png"),
  BIRYANI : require("../../assets/image/chickbiryani.png"),
  NOODLE : require("../../assets/image/noodle.jpeg"),
  DESI : require("../../assets/image/rajma-chawal.jpeg"),
};
